#!/bin/bash
### MODUL-NR. 007 ###
# (c) August 2008 Stefan Schäfer / FSP Computer & Netzwerke
# (c) 2009-2019 Stefan Schäfer / invis-server.org / stefan@invis-server.org
# (c) 2013,2014 Dimitri Asarowski / invis-server.org / dimitri@invis-server.org
# (c) 2013-2017 Ingo Göppert / invis-server.org / ingo@invis-server.org

# License: GPLv3
# Questions: info@invis-server.org

# Das Modul fileserver richtet die Netzwerkfreigaben des invis-sub-Servers ein

# The module fileserver sets up the invis-server network shares

# Dieses Programm ist freie Software. Sie können es unter den Bedingungen der 
# GNU General Public License, wie von der Free Software Foundation veröffentlicht,
# weitergeben und/oder modifizieren, entweder gemäß Version 3 der Lizenz oder
# (nach Ihrer Option) jeder späteren Version.

# Die Veröffentlichung dieses Programms erfolgt in der Hoffnung, daß es Ihnen
# von Nutzen sein wird, aber OHNE IRGENDEINE GARANTIE, sogar ohne die implizite 
# Garantie der MARKTREIFE oder der VERWENDBARKEIT FÜR EINEN BESTIMMTEN ZWECK. 
# Details finden Sie in der GNU General Public License.

# Sie sollten ein Exemplar der GNU General Public License zusammen mit diesem 
# Programm erhalten haben. Falls nicht, siehe <http://www.gnu.org/licenses/>. 

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# include functions
source $SINEINCLUDEDIR/functions

modulename=`basename $0`

clear
windowtitle="Fileserver"
pgsubtitle="Netzwerkfreigaben einrichten"

# Anpassen der Datei smb.conf
path="/etc/samba"
file="smb.conf"

# Freigaben Erweiterung in Samba-Konfiguration einbinden
echo >> $path/$file
echo "## invis-server.org Freigabenkonfiguration einbinden" >> $path/$file
echo "include = /etc/samba/smb.shares.conf" >> $path/$file

# Freigaben werden angelegt
cp $TEMPLATEDIR/fileserver/smb.shares.conf /etc/samba/smb.shares.conf 2>&1| tee -a $LOGFILE

chkservice nmb
chkservice smb
chkservice winbind

#
#cp $TEMPLATEDIR/fileserver/nfs/exports_nfs4 /etc/exports  2>&1| tee -a $LOGFILE
#cp $TEMPLATEDIR/fileserver/nfs/nfs /etc/sysconfig  2>&1| tee -a $LOGFILE
#cat $TEMPLATEDIR/fileserver/nfs/fstab_extention >> /etc/fstab
#mount -a
#path="/etc"
#file="idmapd.conf"
#string="localdomain%$domain"
#changevalues $path $file "$string"
#file=exports
#string="192.168.220.0/24%$netbase/$nmaskshort"
#changevalues $path $file "$string"
